### ISSUE TITLE
Debugging of Task2

### ISSUE THREAD

**Issue by ToKa96** [GwydionJon/Group_1_Developing_Scientific_Software#10]
Started debugging of task2 using the main.py

tried to fix those I've found so far, succesfully creates some DataFrames.

Should you think a bug is due to a bug in FileReader just write it here or open another issue.

- Succesfully used FileReader and Statistical_Analysis.eucl_distance()
- @LeonieKreis there might be a bug in Statistical_Analysis.correlation() or in reading the file
- @GwydionJon check your code and whether nstate_i is correctly transformed, it at least calls the read_numpy()

**Comment by GwydionJon** [comment]
weird bug in num_ana.plot_and_save, where if one plot is set so show as a window all previous plots will also show.
Probably has something to with how matplotlib handels figures, but i don't really have a clue and it is not code breaking
